### ISSUE TITLE
project name conflict with qpm, the Qt Package Manager

### ISSUE THREAD

**Issue by markstos** [pvsr/qbpm#19]
I'm not sure if you care, but this project name conflicts with `qpm`, the Qt Package Manager:

https://repology.org/project/qpm/versions

`qbpm` has no conflicts. 

(There's also a project named `qp`: https://formulae.brew.sh/formula-linux/qp )

**Comment by pvsr** [comment]
It's too bad, `qpm` was much nicer to type. But back to `qbpm` it is.
