### ISSUE TITLE
Could wofi be supported in the future?

### ISSUE THREAD

**Issue by Svanto24** [pvsr/qbpm#22]
Hello!
My understanding is that qbpm supports applescript, rofi, dmenu _and_ dmenu-wl.
Wofi is quite a popular launcher among users of wayland compositors, and from my understanding it's equivalent to rofi, similarly to how dmenu is to dmenu-wl

I'm really impressed with how well qpm integrates with rofi too, it's incredibly convenient, and a very well thought-out tool.

Apologies if it sounds like I am demanding, but I was wondering if wofi could be supported in the future, and if it's not currently planned, what would need to be done to enable its support.

Thank you for reading my inquiry!

**Comment by pvsr** [comment]
Sure, that's a totally reasonable request. I'll take a look at adding wofi support sometime soon.

**Comment by Svanto24** [comment]
Thank you very much!

**Comment by pvsr** [comment]
I added support for wofi, running it as `wofi --dmenu --prompt qutebrowser`.

**Comment by Svanto24** [comment]
That was fast! Thank you so much for your work.
