### ISSUE TITLE
Sources wrong config.py on windows

### ISSUE THREAD

**Issue by simonhughxyz** [pvsr/qbpm#34]
On windows, qutebrowsers `config.py` is located in `~/AppData/Roaming/qutebrowser/config/config.py`.
However qbpm sources `~/.config/qutebrowser/config.py`.

**Comment by simonhughxyz** [comment]
Never mind I just created a symlink to solve the problem

**Comment by simonhughxyz** [comment]
> I'm happy to use the correct path on windows, I just don't have a windows machine myself to test on. Could you run #37 and confirm it finds the config without needing the symlink?

Sorry I've been really busy, ll get back to you once I have some time to test it.

**Comment by pvsr** [comment]
I merged the likely fix, if it still doesn't work for you feel free to reopen the issue.
